{% set name = "oceanum" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceanum-{{ version }}.tar.gz
  sha256: dda7f5caffbf00f7728efb1329a28194df01fda472b637169688fa81651f0013

build:
  entry_points:
    - oceanum = oceanum.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - aiohttp
    - click
    - decorator
    - fsspec
    - geojson-pydantic >=1.0
    - geopandas
    - h5netcdf
    - numpy
    - orjson
    - pandas
    - pyarrow
    - python-snappy
    - requests
    - shapely
    - xarray
    - zarr

test:
  imports:
    - oceanum
  commands:
    - pip check
    - oceanum --help
  requires:
    - pip

about:
  home: https://github.com/oceanum-io/oceanum-python
  summary: Library for oceanum.io services
  dev_url: https://github.com/oceanum-io/oceanum-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
    - seboceanum
    - rafa-guedes
