{% set name = "oceanum" %}
{% set version = "0.15.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceanum-{{ version }}.tar.gz
  sha256: 431ab7874da9b0266dc1b4abe3a3c4a761e7dad18ea91a27f961ddac9fab4238

build:
  entry_points:
    - oceanum = oceanum.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - click
    - decorator
    - fsspec
    - geojson-pydantic >=1.0
    - geopandas
    - h5netcdf
    - numpy
    - orjson
    - pandas
    - pyarrow
    - python-snappy
    - requests
    - shapely
    - xarray
    - zarr

test:
  imports:
    - oceanum
  commands:
    - pip check
    - oceanum --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/oceanum-io/oceanum-python
  summary: Library for oceanum.io services
  dev_url: https://github.com/oceanum-io/oceanum-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
    - seboceanum
    - rafa-guedes
    - tomdurrant
