{% set name = "oceanum" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/oceanum-{{ version }}.tar.gz
  sha256: 761d26c21f6586760e133232bf73f84ca99252f4f9cb6b8a45143bd978a5936f

build:
  entry_points:
    - oceanum = oceanum.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - aiohttp
    - click
    - cftime
    - dask
    - decorator
    - fsspec
    - geojson-pydantic
    - geopandas
    - h5netcdf
    - msgpack-python
    - numcodecs <0.16.0
    - numpy
    - orjson
    - pandas
    - platformdirs
    - pyarrow
    - pydantic
    - python-jsonpath
    - requests
    - shapely
    - tabulate
    - xarray
    - rioxarray
    - zarr <3
    - netcdf4


test:
  imports:
    - oceanum
  commands:
    - pip check
    - oceanum --help
  requires:
    - pip

about:
  home: https://github.com/oceanum-io/oceanum-python
  summary: Library for oceanum.io services
  dev_url: https://github.com/oceanum-io/oceanum-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
    - seboceanum
    - rafa-guedes
    - tomdurrant
