{% set name = "oceanum" %}
{% set version = "1.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/oceanum-{{ version }}.tar.gz
  sha256: 43fc3dd37151d9adf9dc037f6dfad15cf886166637d90c74d5424b68d57affee

build:
  entry_points:
    - oceanum = oceanum.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - pip
  run:
    - python >=3.10
    - aiohttp
    - click
    - cftime
    - dask-core >=2021.3.0
    - decorator
    - fsspec
    - geojson-pydantic >=1.0
    - geopandas
    - h5netcdf
    - numpy
    - orjson
    - pandas
    - platformdirs
    - pyarrow
    - pydantic >=2.0
    - requests
    - shapely
    - xarray
    - rioxarray
    - zarr <3
    - numcodecs <0.16.0
    - msgpack
    - python-jsonpath
    - pip-system-certs

test:
  imports:
    - oceanum
  commands:
    - pip check
    - oceanum --help
  requires:
    - pip

about:
  home: https://github.com/oceanum-io/oceanum-python
  summary: Library for oceanum.io services
  dev_url: https://github.com/oceanum-io/oceanum-python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ondave
    - seboceanum
    - rafa-guedes
